services:
  petric:
    build: {context: ., target: sirf}
    image: synerbi/sirf:ci
    # quick test of installed libraries
    deploy: {resources: {reservations: {devices: [{driver: nvidia, count: all, capabilities: [gpu]}]}}}
    command:
    - python
    - -c
    - |
       import torch, tensorflow as tf
       print("torch:", torch.cuda.is_available(), "| tf:", tf.config.list_physical_devices("GPU"))
  leaderboard:
    build: {context: ., target: leaderboard}
    restart: always
    expose: [6006]
    command: "tensorboard --logdir=/logs --bind_all --window_title='PETRIC Leaderboard' --path_prefix /leaderboard"
    volumes: ["/opt/runner/logs:/logs"]
    healthcheck: {test: "wget --spider localhost:6006/leaderboard"}
    depends_on: [caddy]
    labels:
      virtual.host: petric.tomography.stfc.ac.uk
      virtual.tls-email: casper.da-costa-luis@stfc.ac.uk
      # /leaderboard -> leaderboard:6006
      virtual.port: 6006
      virtual.proxy.matcher: /leaderboard*
      # /data -> caddy:/share/petric
      # /data-wip -> caddy:/share-rw/petric-wip
      # / -> wiki
      virtual.host.directives: |
        handle /data* {
          reverse_proxy http://data
        }
        handle /data-wip* {
          import ext_auth
          reverse_proxy http://data-wip
        }
        redir / https://github.com/SyneRBI/PETRIC/wiki
  caddy:
    build: {context: ., target: caddy-gen, args: {CADDY_UID: 1000, CADDY_GID: 998}}  # user "ubuntu:docker"
    restart: always
    cap_add: [NET_ADMIN]
    volumes:
    - ./caddy:/data/caddy
    - /mnt/share:/share-rw
    - /mnt/share:/share:ro
    - /mnt/share-private:/share-private:ro
    - ./global.caddy:/global.caddy
    - /var/run/docker.sock:/tmp/docker.sock:ro
    environment: {CADDY_SNIPPET: /global.caddy}
    ports: ["80:80", "443:443", "443:443/udp"]
  data:
    image: filebrowser/filebrowser:latest
    restart: always
    volumes: ["/mnt/share/petric:/srv:ro", "./filebrowser/petric.db:/database.db"]
    user: "1005:1005"
    command: [--noauth, -d=/database.db, -b=/data, -l=stdout]
  data-wip:
    image: filebrowser/filebrowser:latest
    restart: always
    volumes: ["/mnt/share/petric-wip:/srv", "./filebrowser/petric-wip.db:/database.db"]
    user: "1005:1005"
    command: [--noauth, -d=/database.db, -b=/data-wip, -l=stdout]
