services:
  petric:
    build: .
    image: synerbi/sirf:ci
    command: "exit 0"
  leaderboard:
    image: synerbi/sirf:ci
    restart: always
    expose: [6006]
    command: "tensorboard --logdir=/logs --bind_all --window_title='PETRIC Leaderboard' --path_prefix /leaderboard"
    volumes: [/opt/runner/logs:/logs]
    healthcheck: {test: "wget --spider localhost:6006/leaderboard"}
    depends_on: [caddy]
    labels:
      virtual.host: petric.tomography.stfc.ac.uk
      virtual.tls-email: casper.da-costa-luis@stfc.ac.uk
      # /leaderboard -> leaderboard:6006
      virtual.port: 6006
      virtual.proxy.matcher: /leaderboard*
      # /data -> caddy:/share/petric
      virtual.host.directives: |
        handle_path /data* {
          root * /share/petric
          file_server {
            browse {
              reveal_symlinks
            }
            pass_thru
          }
        }
        redir / https://github.com/SyneRBI/PETRIC/wiki
  caddy:
    image: casperdcl/caddy-gen
    restart: always
    cap_add: [NET_ADMIN]
    volumes: [./caddy:/data/caddy, /mnt/share:/share, ./global.caddy:/global.caddy, /var/run/docker.sock:/tmp/docker.sock:ro]
    environment: {CADDY_SNIPPET: /global.caddy}
    ports: ["80:80", "443:443", "443:443/udp"]
    healthcheck: {test: "wget --spider localhost/data --header Host:petric.tomography.stfc.ac.uk"}
