#!/usr/bin/env bash
set -euo pipefail

chgrp -Rc $GROUPS .
chmod -Rc g+w .
docker run --rm --gpus all --user root --no-healthcheck -e GITHUB_REPOSITORY -e GITHUB_REF_NAME \
  -e TQDM_MININTERVAL=1 \
  -e NUMEXPR_MAX_THREADS=24 \
  -e RUNNER_GID=$GROUPS \
  -v /mnt/share:/mnt/share:ro \
  -v /opt/runner:/o:rw \
  -v .:/w:rw -w /w \
  synerbi/sirf:ci \
  /o/petric-main.sh
