#!/usr/bin/env bash
set -euo pipefail

export NB_GID=$(getent group runner | cut -d: -f3)
chgrp -Rc $NB_GID .
chmod -Rc g+w .
docker run --rm --gpus all -u root -e NB_GID --no-healthcheck -e GITHUB_REPOSITORY -e GITHUB_REF_NAME \
  -e TQDM_MININTERVAL=1 \
  -e NUMEXPR_MAX_THREADS=24 \
  -v /mnt/share-public/petric/2:/mnt/share/petric:ro \
  -v /opt/runner:/o:ro \
  -v /opt/runner/logs/2:/logs:rw \
  -v .:/w:rw -w /w \
  ghcr.io/synerbi/sirf:petric2 \
  /o/petric-main.sh
